name: CI Github Actions Python App

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v3

      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "./requirements.txt"
          
      - name: Run db.py script
        run: python db.py --print_all_data

      - name: Run unit tests
        run: |
          python -m unittest discover tests     

      - name: Checkout code
        uses: actions/checkout@v3
