name: CI Github Actions Python App

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v3

      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install Python dependencies
        run: pip install -r requirements.txt
        
      - name: Run db.py script
        run: python db.py --print_all_data

      - name: Install tox and any other packages
        run: pip install tox
      - name: Run tox
        # Run tox using the version of Python in `PATH`
        run: tox -e py
        
      - name: Check API
        run: |
          status_code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:5000)
           if [ "$status_code" == "200" ]; then
             echo "API is running successfully!"
           else
             echo "API is not running. Status code: $status_code"
             exit 1
           fi
